language: go

go:
   - 1.6

install:
- export PATH=$PATH:$HOME/gopath/bin
- go get github.com/lcaballero/go-gh/./...
- go install github.com/lcaballero/go-gh
- go install github.com/lcaballero/exam

script: go test --race ./...